language: minimal

stages:
  - name: fast_check
  - name: build_and_pack

env:
  global:
    
jobs:
  include:
    - stage: fast_check
      name: Shell linter
      language: shell
      script:
        - bash -c 'shopt -s globstar; shellcheck -e SC1117 **/*.sh'

    - stage: fast_check
      name: Fast build
      os: linux
      language: minimal
      services:
        - docker
      before_install:
        - docker pull fritzing/build:bionic
      script:
        - docker/build-linux.sh

      after_success:
        - tools/aws_tasks.sh synchronize_up

    - stage: build_and_pack
      name: Bionic
      os: linux
      language: minimal
      services:
        - docker
      before_install:
        - tools/aws_tasks.sh setup
        - docker pull fritzing/build:bionic
      script:
        - docker/release-linux.sh bionic $TRAVIS_COMMIT-$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER.bionic
        - tools/aws_tasks.sh store_with_md5 . fritzing-$TRAVIS_COMMIT-$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER.bionic.linux.AMD64.tar.bz2

      after_success:
        - tools/aws_tasks.sh synchronize_up

    - stage: build_and_pack
      name: Fedora
      os: linux
      language: minimal
      services:
        - docker
      before_install:
        - tools/aws_tasks.sh setup
        - docker pull fritzing/build:fedora-30
      script:
        - docker/release-linux.sh fedora-30 $TRAVIS_COMMIT-$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER.fedora-30
        - tools/aws_tasks.sh store_with_md5 . fritzing-$TRAVIS_COMMIT-$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER.fedora-30.linux.AMD64.tar.bz2

      after_success:
        - tools/aws_tasks.sh synchronize_up

    - stage: build_and_pack
      os: osx
      language: cpp
      osx_image: xcode10.2
      cache:
        directories:
          ../libgit2/build

      addons:
        homebrew:
          packages:
          - qt5
          update: false

      before_install:
        - mkdir -p ../libgit2/build
        - wget -q -O - https://github.com/libgit2/libgit2/archive/v0.28.1.tar.gz | tar xz && mv libgit2-0.28.1/* ../libgit2/
        - (cd ../libgit2/build && cmake -D BUILD_SHARED_LIBS=OFF .. && cmake --build .)
        - (cd .. && wget -q -O - https://dl.bintray.com/boostorg/release/1.70.0/source/boost_1_70_0.tar.bz2 | tar xj)
        - tools/aws_tasks.sh setup
      script:
        - ls /usr/local/opt
        - tools/deploy_fritzing_mac.sh
        - mv ../deploy-app/Fritzing.dmg fritzing-$TRAVIS_COMMIT-$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER.mojave.10.2.dmg
        - tools/aws_tasks.sh store_with_md5 . fritzing-$TRAVIS_COMMIT-$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER.mojave.10.2.dmg

      after_success:
        - tools/aws_tasks.sh synchronize_up

    - stage: build_and_pack
      os: windows
      language: cpp

      before_install:
        - curl -L http://download.qt-project.org/official_releases/online_installers/qt-unified-windows-x86-online.exe --output qt-installer.exe
        - ./qt-installer.exe --script ./tools/qt_installer_noninteractive.qs
        - curl -fsSL https://github.com/libgit2/libgit2/archive/v0.28.1.zip -o libgit2.zip && 7z x libgit2.zip && mv libgit2-0.28.1 ../libgit2
        - (mkdir ../libgit2/build64 && cd ../libgit2/build64 && cmake -G "Visual Studio 15 2017 Win64" .. && cmake --build . --config Release)
        - (cd .. && curl -L https://dl.bintray.com/boostorg/release/1.70.0/source/boost_1_70_0.tar.bz2 | tar xj)
        - tools/aws_tasks.sh setup

      script:
          - tools/build-windows.bat "$TRAVIS_COMMIT"-$TRAVIS_BRANCH-"$TRAVIS_BUILD_NUMBER"
          - tools/aws_tasks.sh store_with_md5 $TRAVIS_BUILD_DIR/../release64 fritzing-$TRAVIS_COMMIT-$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER.windows.64.zip

      after_success:
        - tools/aws_tasks.sh synchronize_up

    
